import { GetLoginActivityCsReq, GetLoginActivityScRsp, LoginActivityData } from "../../resources/autogenerated/cs.activity";
import { PacketContext, RouteManager } from "../network/route";

export class ActivityHandler{

    constructor(routeManager: RouteManager){
        routeManager.on(GetLoginActivityCsReq, this.GetLoginActivityCsReq);
    }

    public GetLoginActivityCsReq(context: PacketContext<GetLoginActivityCsReq>){
        const rsp = GetLoginActivityScRsp.create();
        rsp.retcode = 0;
        rsp.loginActivityList = [];
        context.send(GetLoginActivityScRsp, rsp);
    }
}