import { PlayerGetTokenCsReq, PlayerGetTokenScRsp, PlayerKeepAliveNotify, PlayerLoginCsReq } from "../../resources/autogenerated/cs.player";
import { PacketContext, RouteManager } from "../network/route";

export class AuthHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(PlayerGetTokenCsReq, this.PlayerGetTokenCsReq);
    }

    public PlayerGetTokenCsReq(context: PacketContext<PlayerGetTokenCsReq>){
        const rsp = PlayerGetTokenScRsp.create();
        rsp.secretKeySeed = BigInt(0);
        rsp.uid = context.request.uid!;
        context.send(PlayerGetTokenScRsp, rsp);
    }
}