import { PlayerBasicInfo } from "../../resources/autogenerated/common.define";
import { PlayerGetTokenCsReq, PlayerGetTokenScRsp, PlayerLoginCsReq, PlayerLoginScRsp } from "../../resources/autogenerated/cs.player";
import { PacketContext, RouteManager } from "../network/route";

export class AuthHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(PlayerGetTokenCsReq, this.PlayerGetTokenCsReq);
        routeManager.on(PlayerLoginCsReq, this.PlayerLoginCsReq);
    }

    public PlayerGetTokenCsReq(context: PacketContext<PlayerGetTokenCsReq>){
        const rsp = PlayerGetTokenScRsp.create();
        rsp.secretKeySeed = BigInt(0);
        rsp.uid = context.request.uid!;
        context.send(PlayerGetTokenScRsp, rsp);
    }

    public PlayerLoginCsReq(context: PacketContext<PlayerLoginCsReq>){
        const basicInfo = PlayerBasicInfo.create();
        basicInfo.exp = 0;
        basicInfo.hcoin = 100000;
        basicInfo.level = 60;
        basicInfo.mcoin = 100000;
        basicInfo.nickname = "CloudySR";
        basicInfo.scoin = 100000;
        basicInfo.stamina = 1000;
        basicInfo.worldLevel = 8;

        const rsp = PlayerLoginScRsp.create();
        rsp.retcode = 0;
        rsp.basicInfo = basicInfo;
        rsp.serverTimestampMs = BigInt(Date.now());
        rsp.loginRandom = context.request.loginRandom!;
        rsp.stamina = 1000;
        rsp.isNewPlayer = true;
        rsp.isRelay = true;

        context.send(PlayerLoginScRsp, rsp);
    }
}