import { GetExpeditionDataCsReq, GetExpeditionDataScRsp } from "../../resources/autogenerated/cs.expedition";
import { PacketContext, RouteManager } from "../network/route";

export class ExpeditionHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetExpeditionDataCsReq, this.GetExpeditionDataCsReq);
    }

    public GetExpeditionDataCsReq(context: PacketContext<GetExpeditionDataCsReq>){
        const rsp = GetExpeditionDataScRsp.create();
        rsp.retcode = 0;
        rsp.expedtionList = [];
        rsp.teamCount = 4;
        rsp.unlockedExpeditionIdList = [];
        context.send(GetExpeditionDataScRsp, rsp);
    }
}