import { GachaInfo, GetGachaInfoCsReq, GetGachaInfoScRsp } from "../../resources/autogenerated/cs.gacha";
import { PacketContext, RouteManager } from "../network/route";

export class GachaHandler {
    constructor(routeManager: RouteManager) {
        routeManager.on(GetGachaInfoCsReq, this.GetGachaInfoCsReq);
    }

    public GetGachaInfoCsReq(context: PacketContext<GetGachaInfoCsReq>): void {
        const rsp = GetGachaInfoScRsp.create();
        rsp.retcode = 0;
        rsp.gachaInfoList = [];
        rsp.gachaRandom = 1;
        rsp.retcode = 0;
        rsp.todaySingleGachaMaxCnt = 100;
        rsp.todayTotalGachaCnt = 0;
        rsp.todayTotalGachaMaxCnt = 100;
        context.send(GetGachaInfoScRsp, rsp);
    }
}