import { AvatarType, Gender, HeroBasicType } from "../../resources/autogenerated/common.define";
import { AvatarSkillTree } from "../../resources/autogenerated/common.gamecore";
import { Avatar, GetAvatarDataCsReq, GetAvatarDataScRsp } from "../../resources/autogenerated/cs.avatar";
import { ExtraLineupType, GetAllLineupDataCsReq, GetAllLineupDataScRsp, LineupAvatar, LineupInfo } from "../../resources/autogenerated/cs.lineup";
import { GetHeroBasicTypeInfoCsReq, GetHeroBasicTypeInfoScRsp, GetHeroPathCsReq, GetHeroPathScRsp, HeroBasicTypeInfo } from "../../resources/autogenerated/cs.player";
import { PacketContext, RouteManager } from "../network/route";

export class HeroHandler {
    constructor(routeManager: RouteManager) {
        routeManager.on(GetHeroBasicTypeInfoCsReq, this.GetHeroBasicTypeInfoCsReq);
        routeManager.on(GetHeroPathCsReq, this.GetHeroPathCsReq);
        routeManager.on(GetAvatarDataCsReq, this.GetAvatarDataCsReq);
        routeManager.on(GetAllLineupDataCsReq, this.GetAllLineupDataCsReq);
    }

    public GetAllLineupDataCsReq(context: PacketContext<GetAllLineupDataCsReq>) {
        const rsp = GetAllLineupDataScRsp.create();
        rsp.retcode = 0;
        rsp.lineupList = []
        context.send(GetAllLineupDataScRsp, rsp);
    }

    public GetAvatarDataCsReq(context: PacketContext<GetAvatarDataCsReq>) {
        console.log(context.request.baseAvatarIdList);
        const rsp = GetAvatarDataScRsp.create();
        rsp.avatarList = [
            Avatar.create({
                baseAvatarId: 1001,
                exp: 0,
                level: 1,
                promotion: 1,
                rank: 1,
                skilltreeList: [],
                equipmentUniqueId: 13501,
                equipRelicList: [],
            })
        ];

        rsp.retcode = 0;
        rsp.isAll = context.request.isGetAll!;
        context.send(GetAvatarDataScRsp, rsp);
    }

    public GetHeroPathCsReq(context: PacketContext<GetHeroPathCsReq>) {
        const rsp = GetHeroPathScRsp.create();
        rsp.retcode = 0;
        rsp.heroPathList = [];
        context.send(GetHeroPathScRsp, rsp);
    }

    public GetHeroBasicTypeInfoCsReq(context: PacketContext<GetHeroBasicTypeInfoCsReq>) {
        const rsp = GetHeroBasicTypeInfoScRsp.create();
        rsp.retcode = 0;
        rsp.gender = Gender.GenderMan;
        rsp.isPlayerInfoModified = true;
        rsp.isGenderModified = true;
        rsp.heroPathList = [];
        rsp.curBasicType = HeroBasicType.BoyKnight;
        rsp.basicTypeInfoList = [
            HeroBasicTypeInfo.create({
                basicType: HeroBasicType.BoyKnight,
                rank: 1,
                skillTreeList: []
            })
        ];
        context.send(GetHeroBasicTypeInfoScRsp, rsp);
    }
}