import { GetBagCsReq, GetBagScRsp } from "../../resources/autogenerated/cs.item";
import { PacketContext, RouteManager } from "../network/route";

export class InventoryHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetBagCsReq, this.GetBagCsReq);
    }

    public GetBagCsReq(context: PacketContext<GetBagCsReq>){
        const rsp = GetBagScRsp.create();
        rsp.retcode = 0;
        rsp.equipmentList = [];
        rsp.materialList = [];
        rsp.relicList = [];
        rsp.rogueItemList = [];
        rsp.waitDelResourceList = [];
        context.send(GetBagScRsp, rsp);
    }
}