import { GetMailCsReq, GetMailScRsp } from "../../resources/autogenerated/cs.mail";
import { PacketContext, RouteManager } from "../network/route";

export class MailHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetMailCsReq, this.GetMailCsReq);
    }

    public GetMailCsReq(context: PacketContext<GetMailCsReq>){
        const rsp = GetMailScRsp.create();
        rsp.retcode = 0;
        rsp.mailList = [];
        rsp.noticeMailList = [];
        rsp.isEnd = false;
        rsp.start = 0;
        rsp.totalNum = 0;
        context.send(GetMailScRsp, rsp);
    }
}