import { readFileSync } from "fs";
import path from "path";
import { FeatureSwitchInfo, FeatureSwitchParam, FeatureSwitchType } from "../../resources/autogenerated/common.define";
import { MissionStatus } from "../../resources/autogenerated/cs.common";
import { FinishTalkMissionCsReq, GetMissionDataCsReq, GetMissionDataScRsp, GetMissionEventDataCsReq, GetMissionEventDataScRsp, GetMissionStatusCsReq, GetMissionStatusScRsp, Mission } from "../../resources/autogenerated/cs.mission";
import { UpdateFeatureSwitchScNotify } from "../../resources/autogenerated/cs.player";
import { GetQuestDataCsReq, GetQuestDataScRsp } from "../../resources/autogenerated/cs.quest";
import { PacketContext, RouteManager } from "../network/route";

export class MissionHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetMissionStatusCsReq, this.GetMissionStatusCsReq);
        routeManager.on(GetMissionDataCsReq, this.GetMissionDataCsReq);
        routeManager.on(GetMissionEventDataCsReq, this.GetMissionEventDataCsReq);
        routeManager.on(GetQuestDataCsReq, this.GetQuestDataCsReq);
        routeManager.on(FinishTalkMissionCsReq, this.FinishTalkMissionCsReq);
    }

    public FinishTalkMissionCsReq(context: PacketContext<FinishTalkMissionCsReq>){
        const rsp = GetMissionDataScRsp.create();
        rsp.retcode = 0;
        rsp.missionList = [];
        context.send(GetMissionDataScRsp, rsp);
    }

    public GetQuestDataCsReq(context: PacketContext<GetQuestDataCsReq>){
        const rsp = GetQuestDataScRsp.create();
        rsp.retcode = 0;
        rsp.questList = [];
        rsp.takenAchievementLevelList = [];
        rsp.totalAchievementExp = 0;
        context.send(GetQuestDataScRsp, rsp);
    }

    public GetMissionEventDataCsReq(context: PacketContext<GetMissionEventDataCsReq>){
        const rsp = GetMissionEventDataScRsp.create();
        rsp.challengeEventId = 0;
        rsp.retcode = 0;
        rsp.missionEventList = [];
        context.send(GetMissionEventDataScRsp, rsp);
    }

    public GetMissionDataCsReq(context: PacketContext<GetMissionDataCsReq>){
        const rsp = GetMissionDataScRsp.create();
        rsp.retcode = 0;
        rsp.missionList = [];
    }

    public GetMissionStatusCsReq(context: PacketContext<GetMissionStatusCsReq>){
        const rsp = GetMissionStatusScRsp.create();
        rsp.retcode = 0;
        rsp.finishedMainMissionIdList = [
            1000101, 
            1000112, 
            1000113, 
            1000201, 
            1000202, 
            1000204, 
            1000301, 
            1000401, 
            1000402, 
            1000410, 
            1000510,
            1000601,
            1010301, 
            1010302, 
            1010401,
            1010403, 
            1010701,
            1011403,
            1010202,
            1010902,
            1011102,
            4010101
        ];
        rsp.unfinishedMainMissionIdList = context.request.mainMissionIdList!;
        rsp.missionEventStatusList = context.request.missionEventIdList!.map(id => {
            return Mission.create({
                id: id,
                progress: 0,
                status: MissionStatus.MISSION_FINISH
            });
        })
        rsp.subMissionStatusList = context.request.subMissionIdList!.map(id => {
            return Mission.create({
                id: id,
                progress: 0,
                status: MissionStatus.MISSION_FINISH
            });
        })

        context.send(GetMissionStatusScRsp, rsp);
    }
}