import { GetPrestigeInfoCsReq, GetPrestigeInfoScRsp, PrestigeInfo } from "../../resources/autogenerated/cs.prestige";
import { PacketContext, RouteManager } from "../network/route";

export class PrestigeHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetPrestigeInfoCsReq, this.GetPrestigeInfoCsReq);
    }

    public GetPrestigeInfoCsReq(context: PacketContext<GetPrestigeInfoCsReq>){
        const rsp = GetPrestigeInfoScRsp.create();
        rsp.retcode = 0;
        rsp.prestigeInfo = PrestigeInfo.create();
        context.send(GetPrestigeInfoScRsp, rsp);
    }
}