import { GetLevelRewardCsReq, GetLevelRewardScRsp, GetLevelRewardTakenListCsReq, GetLevelRewardTakenListScRsp } from "../../resources/autogenerated/cs.player";
import { PacketContext, RouteManager } from "../network/route";

export class RewardHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetLevelRewardTakenListCsReq, this.GetLevelRewardTakenListCsReq);
    }

    public GetLevelRewardTakenListCsReq(context: PacketContext<GetLevelRewardTakenListCsReq>){
        const rsp = GetLevelRewardTakenListScRsp.create();
        rsp.retcode = 0;
        rsp.takenLevelList = [];
        context.send(GetLevelRewardTakenListScRsp, rsp);
    }
}