import { GetRogueInfoCsReq, GetRogueInfoScRsp, RogueChallengeInfo, RogueInfo } from "../../resources/autogenerated/cs.rogue";
import { PacketContext, RouteManager } from "../network/route";

export class RogueHandler{

    constructor(routeManager: RouteManager){
        routeManager.on(GetRogueInfoCsReq, this.GetRogueInfoCsReq);
    }

    public GetRogueInfoCsReq(context: PacketContext<GetRogueInfoCsReq>){
        const rsp = GetRogueInfoScRsp.create();
        rsp.retcode = 0;
        rsp.rogueInfo = RogueInfo.create();
        rsp.rogueChallengeInfo = RogueChallengeInfo.create();
        context.send(GetRogueInfoScRsp, rsp);
    }
}