import { GetTutorialCsReq, GetTutorialGuideCsReq, GetTutorialGuideScRsp, GetTutorialScRsp, Tutorial, TutorialGuide, TutorialStatus, UnlockTutorialCsReq } from "../../resources/autogenerated/cs.tutorial";
import { PacketContext, RouteManager } from "../network/route";

export class TutorialHandler{
    constructor(routeManager: RouteManager){
        routeManager.on(GetTutorialCsReq, this.GetTutorialCsReq);
        routeManager.on(GetTutorialGuideCsReq, this.GetTutorialGuideCsReq);
        routeManager.on(UnlockTutorialCsReq, this.UnlockTutorialCsReq);
    }

    public UnlockTutorialCsReq(context: PacketContext<UnlockTutorialCsReq>){
        const rsp = GetTutorialScRsp.create();
        rsp.retcode = 0;
        rsp.tutorialList = [
            Tutorial.create({
                id: context.request.tutorialId!,
                status: TutorialStatus.TUTORIAL_UNLOCK
            })
        ]
        context.send(GetTutorialScRsp, rsp);
    }

    public GetTutorialGuideCsReq(context: PacketContext<GetTutorialGuideCsReq>){
        const rsp = GetTutorialGuideScRsp.create();
        rsp.retcode = 0;
        rsp.tutorialGuideList = [];
        context.send(GetTutorialGuideScRsp, rsp);
    }
    
    public GetTutorialCsReq(context: PacketContext<GetTutorialCsReq>){
        const rsp = GetTutorialScRsp.create();
        rsp.retcode = 0;
        rsp.tutorialList = []
        context.send(GetTutorialScRsp, rsp);
    }
}