import { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { Gateserver } from "../../../resources/autogenerated/cs.player";
import { Crypto } from "../../utils/crypto";

export default async function dispatchController(fastify: FastifyInstance) {
    fastify.get("/query_dispatch", async (request, reply) => {
        reply.code(200).send(JSON.stringify({
            retcode: 0,
            region_list: [
                {
                    dispatch_url: "https://127.0.0.1/query_cur_region",
                    env_type: 2,
                    name: "cloudy_sr_ts",
                    title: ""
                },
            ]
        }));
    });

    
    fastify.get('/query_cur_region',async (request, reply) => {
        const rsp = Gateserver.create({
            regionName: "cloudy_sr_ts",
            ip: "127.0.0.1",
            port: 23301,
            //clientSecretKey: Crypto.ec2b.ec2b.toString('base64')
        });

        const encodedBuffer = Buffer.from(Gateserver.toBinary(rsp));
        reply.code(200).send(encodedBuffer.toString('base64'));
    });
}
