import { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { QueryCurRegionRsp } from "../../../resources/autogenerated/QueryCurRegionRsp";
import { Crypto } from "../../utils/crypto";

export default async function dispatchController(fastify: FastifyInstance) {
    fastify.get("/query_dispatch", async (request, reply) => {
        reply.code(200).send(JSON.stringify({
            retcode: 0,
            region_list: [
                {
                    dispatch_url: "https://127.0.0.1/query_cur_region",
                    env_type: 2,
                    name: "cloudy_sr_ts",
                    title: ""
                },
            ]
        }));
    });

    
    fastify.get('/query_cur_region',async (request, reply) => {
        const rsp = QueryCurRegionRsp.create({
            regionId: "cloudy_sr_ts",
            gateserverAddress: "127.0.0.1",
            gateserverPort: 23301,
            unk1: true,
            unk2: true,
            unk3: 2,
            asb: "https://autopatchos.starrails.com/asb/V0.70Live/output_626209_0790f92a1a",
            designData: "https://autopatchos.starrails.com/design_data/V0.70Live/output_626257_6a0b73fec2",
            lua: "https://autopatchos.starrails.com/lua/V0.70Live/output_624933_b1cf190af7",
            annoucementLink: "https://webstatic-sea.hoyoverse.com/hkrpg/event/im-service/index.html?im_out=false&sign_type=2&auth_appid=im_ccs&authkey_ver=1&game_biz=hkrpg_global&win_direction=portrait",
            regionCustomConfig: "|fk|add",
            secretKey: Crypto.ec2b.ec2b.toString('base64')
        });

        const encodedBuffer = Buffer.from(QueryCurRegionRsp.toBinary(rsp));
        reply.code(200).send(encodedBuffer.toString('base64'));
    });
}
